#!/usr/bin/env python3
"""Inline SVG charts.

Deliberately hand-written rather than generated by a library: these carry
information the prose can't show as quickly, they weigh a couple of kilobytes,
they need no scripts (the CSP forbids them anyway), and they inherit the site's
colors from CSS variables so they stay in step with the theme.

Every chart is role="img" with a <title> and <desc> so it reads sensibly to
screen readers, and the numbers always appear in the surrounding text too — the
chart is never the only place a fact lives.
"""

CHART_CSS = """
  .chart {
    margin: 34px 0; padding: 24px 26px 20px; background: var(--surface);
    border: 1px solid var(--line); border-radius: var(--radius);
  }
  .chart svg { width: 100%; height: auto; display: block; overflow: visible; }
  .chart-title {
    font-size: 13.5px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;
    color: var(--pine-strong); margin: 0 0 16px;
  }
  .chart-note { font-size: 15px; color: var(--ink-faint); margin: 14px 0 0; max-width: 60ch; }
  .chart text { font-family: 'Atkinson Hyperlegible', sans-serif; }
  .c-lab { font-size: 13px; fill: var(--ink-soft); }
  .c-num { font-size: 15px; font-weight: 700; fill: var(--ink); }
  .c-key { font-size: 12.5px; fill: var(--ink-faint); }
"""


def _wrap(title, svg, note):
    return (f'      <div class="chart">\n        <p class="chart-title">{title}</p>\n'
            f'{svg}\n        <p class="chart-note">{note}</p>\n      </div>\n')


# ---------------------------------------------------------------- thresholds
def thresholds_timeline():
    # Ages cluster tightly between 59 and 67, so labels alternate between two
    # rows with a leader line — otherwise they overlap into mush.
    marks = [
        (50, 'Vaccines start', 'real'),
        (55, 'Discounts', 'soft'),
        (59.5, '401(k) penalty ends', 'real'),
        (62, 'Social Security opens', 'real'),
        (65, 'Medicare', 'hard'),
        (67, 'Full retirement age', 'real'),
        (73, 'Withdrawals required', 'real'),
    ]
    lo, hi, x0, x1 = 48, 75, 40, 720
    fill = {'hard': 'var(--gold)', 'real': 'var(--pine)', 'soft': 'var(--ink-faint)'}

    def X(a):
        return x0 + (a - lo) / (hi - lo) * (x1 - x0)

    parts = [f'<line x1="{x0}" y1="70" x2="{x1}" y2="70" stroke="var(--line)" stroke-width="2"/>']
    for i, (age, label, kind) in enumerate(marks):
        x = round(X(age), 1)
        r = 9 if kind == 'hard' else 7
        low = (i % 2 == 1)
        ly = 116 if low else 92
        if low:
            parts.append(f'<line x1="{x}" y1="79" x2="{x}" y2="{ly - 12}" stroke="var(--line)" '
                         'stroke-width="1.5"/>')
        parts.append(f'<circle cx="{x}" cy="70" r="{r}" fill="{fill[kind]}"/>')
        if kind == 'hard':
            parts.append(f'<circle cx="{x}" cy="70" r="16" fill="var(--gold)" opacity="0.2"/>')
        shown = str(age).replace('.5', '½')
        parts.append(f'<text class="c-num" x="{x}" y="52" text-anchor="middle">{shown}</text>')
        parts.append(f'<text class="c-lab" x="{x}" y="{ly}" text-anchor="middle">{label}</text>')
    svg = ('        <svg viewBox="0 0 760 140" role="img" aria-labelledby="thT thD">\n'
           '          <title id="thT">Age thresholds from 50 to 73</title>\n'
           '          <desc id="thD">A horizontal age axis marking seven thresholds: vaccines at 50, '
           'private discounts at 55, the end of the retirement-account penalty at 59 and a half, '
           'Social Security and the parks pass at 62, Medicare enrollment at 65, full retirement age '
           'at 67, and required withdrawals at 73. Medicare at 65 is highlighted as the one with a '
           'permanent penalty for missing it.</desc>\n          '
           + '\n          '.join(parts) + '\n        </svg>')
    return _wrap('The decade, in order',
                 svg,
                 'Gold marks the one threshold with a permanent penalty attached. Gray is marketing.')


# ---------------------------------------------------------------- IEP window
def enrolment_window():
    months = ['−3', '−2', '−1', '65th', '+1', '+2', '+3']
    w, gap, x0 = 88, 8, 30
    parts = []
    for i, m in enumerate(months):
        x = x0 + i * (w + gap)
        birthday = (i == 3)
        best = i < 3
        fill = 'var(--gold-soft)' if birthday else ('var(--surface-2)' if best else 'var(--bg)')
        stroke = 'var(--gold)' if birthday else 'var(--line)'
        parts.append(f'<rect x="{x}" y="40" width="{w}" height="58" rx="8" fill="{fill}" '
                     f'stroke="{stroke}" stroke-width="{2 if birthday else 1.5}"/>')
        parts.append(f'<text class="c-num" x="{x + w/2}" y="75" text-anchor="middle">{m}</text>')
    parts.append(f'<line x1="{x0}" y1="118" x2="{x0 + 3*(w+gap) + w}" y2="118" '
                 'stroke="var(--pine)" stroke-width="3" stroke-linecap="round"/>')
    parts.append(f'<text class="c-key" x="{x0}" y="136">Sign up here and coverage starts on time</text>')
    parts.append(f'<text class="c-key" x="{x0 + 4*(w+gap)}" y="136">Later start, possible gap</text>')
    svg = ('        <svg viewBox="0 0 700 150" role="img" aria-labelledby="iepT iepD">\n'
           '          <title id="iepT">The seven-month Medicare enrollment window</title>\n'
           '          <desc id="iepD">Seven monthly blocks: the three months before your 65th birthday '
           'month, the birthday month itself, and the three months after. Enrolling in the first three '
           'means coverage begins on time; enrolling later can leave a gap.</desc>\n          '
           + '\n          '.join(parts) + '\n        </svg>')
    return _wrap('Your Initial Enrollment Period',
                 svg,
                 'Seven months, centered on your birthday month. The early half is the better half.')


# ---------------------------------------------------------------- fraud share
def fraud_share():
    rows = [('Share of all complaints filed', 20, 'var(--pine)'),
            ('Share of all money lost', 37, 'var(--gold)')]
    x0, bw, top = 250, 380, 34
    parts = []
    for i, (label, pct, color) in enumerate(rows):
        y = top + i * 62
        parts.append(f'<text class="c-lab" x="{x0 - 16}" y="{y + 21}" text-anchor="end">{label}</text>')
        parts.append(f'<rect x="{x0}" y="{y}" width="{bw}" height="30" rx="6" fill="var(--surface-2)"/>')
        parts.append(f'<rect x="{x0}" y="{y}" width="{round(bw * pct / 100)}" height="30" rx="6" '
                     f'fill="{color}"/>')
        parts.append(f'<text class="c-num" x="{x0 + round(bw * pct / 100) + 12}" y="{y + 21}">{pct}%</text>')
    svg = ('        <svg viewBox="0 0 700 165" role="img" aria-labelledby="frT frD">\n'
           '          <title id="frT">People aged 60 and over: share of complaints versus share of losses</title>\n'
           '          <desc id="frD">Two bars. Adults 60 and over filed 20 percent of all fraud complaints '
           'reported to the FBI in 2025 but accounted for 37 percent of the money lost.</desc>\n          '
           + '\n          '.join(parts) + '\n        </svg>')
    return _wrap('Where the money actually goes',
                 svg,
                 'FBI IC3, 2025. A fifth of the reports, well over a third of the losses — because that '
                 'is where the retirement accounts are.')


# ---------------------------------------------------------------- Part D
def part_d_phases():
    segs = [('Deductible', 615, 'var(--surface-2)', 'var(--ink)'),
            ('You pay a share', 1485, 'var(--pine)', '#FBFAF4')]
    total = 2100
    x0, bw = 40, 620
    parts, x = [], x0
    for label, amount, fill, ink in segs:
        w = round(bw * amount / total)
        parts.append(f'<rect x="{x}" y="46" width="{w}" height="46" fill="{fill}" '
                     f'stroke="var(--line)" stroke-width="1"/>')
        parts.append(f'<text class="c-lab" x="{x + w/2}" y="74" text-anchor="middle" '
                     f'fill="{ink}">{label}</text>')
        x += w
    parts.append(f'<rect x="{x}" y="46" width="{x0 + bw + 20 - x}" height="46" fill="var(--gold-soft)" '
                 'stroke="var(--gold)" stroke-width="1.5"/>')
    parts.append(f'<text class="c-lab" x="{(x + x0 + bw + 20)/2}" y="74" text-anchor="middle">$0</text>')
    parts.append(f'<text class="c-num" x="{x0}" y="34">$0</text>')
    parts.append(f'<text class="c-num" x="{x0 + round(bw*615/total)}" y="34" text-anchor="middle">$615</text>')
    parts.append(f'<text class="c-num" x="{x}" y="34" text-anchor="middle">$2,100</text>')
    parts.append(f'<text class="c-key" x="{x + 8}" y="112">Plan covers your covered drugs '
                 'for the rest of the year</text>')
    svg = ('        <svg viewBox="0 0 700 125" role="img" aria-labelledby="pdT pdD">\n'
           '          <title id="pdT">Part D out-of-pocket spending in 2026</title>\n'
           '          <desc id="pdD">A bar showing three phases: a deductible of up to 615 dollars, then '
           'a period where you pay a share of costs, and then zero cost for covered drugs once your '
           'out-of-pocket spending reaches 2,100 dollars.</desc>\n          '
           + '\n          '.join(parts) + '\n        </svg>')
    return _wrap('What you pay across the year',
                 svg,
                 'Premiums do not count toward the $2,100, and neither do drugs your plan does not cover.')
