'use strict';
// Regression scenarios for the retirement calculator. Each scenario sets
// concrete DOM field values (matching retirement-strategy-model.html ids)
// and is independently reconciled against ssa-reference.js.
//
// `person(prefix)` builds a person object shaped like ssa-reference.js wants,
// reading straight from the same field values passed to the browser so the
// two never drift apart by hand-transcription error.
function personFields(prefix, f) {
  return {
    birthYear: f[prefix + 'birth-year'],
    birthMonth: f[prefix + 'birth-month'] || 1,
    retireAge: f[prefix + 'retire-age'],
    currentWages: f[prefix + 'wages'] || 0,
    futureWages: f[prefix + 'future-wages'] || 0,
    avgWages: f[prefix + 'avg-wages'] || 0,
    yearsWorked: f[prefix + 'years-worked'],
    override: f[prefix + 'ss-override'] || 0,
    overrideAge: f[prefix + 'ss-override-age'] || 62,
    countableEarnings: f[prefix + 'countable-earnings'] === '' ? (f[prefix + 'wages'] || 0) : (f[prefix + 'countable-earnings'] || 0),
  };
}

const SCENARIOS = [
  {
    id: 'single_baseline',
    description: 'Single, standard 35-year average earner ($60k), retiring at 65',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 65,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 350000, 'roth-balance': 100000, 'taxable-balance': 50000,
      'annual-contrib': 6000, 'employer-contrib': 3000,
      'return-rate': 3, 'annual-spending': 65000, horizon: 85,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_short_career',
    description: 'Single, only 18 years of covered work (tests 35-year zero-padding)',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 3, 'retire-age': 67,
      wages: 70000, 'future-wages': 70000, 'avg-wages': 0, 'years-worked': 20,
      'ss-override': 0,
      'traditional-balance': 400000, 'roth-balance': 50000, 'taxable-balance': 20000,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 55000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_high_earner',
    description: 'Single, high earner consistently at/above the taxable wage cap',
    household: 'single',
    fields: {
      'birth-year': 1962, 'birth-month': 11, 'retire-age': 67,
      wages: 250000, 'future-wages': 250000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 1200000, 'roth-balance': 300000, 'taxable-balance': 200000,
      'annual-contrib': 23000, 'employer-contrib': 10000,
      'return-rate': 4, 'annual-spending': 120000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_ssa_override',
    description: 'Single, enters a real SSA statement estimate ($2,400/mo at age 67)',
    household: 'single',
    fields: {
      'birth-year': 1963, 'birth-month': 4, 'retire-age': 67,
      wages: 0, 'future-wages': 0, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 2400, 'ss-override-age': 67,
      'traditional-balance': 500000, 'roth-balance': 150000, 'taxable-balance': 60000,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 70000, horizon: 85,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
    ssKnown: 'yes',
  },
  {
    id: 'single_avg_wages',
    description: 'Single, high current pay but a much lower career-average (raise scenario)',
    household: 'single',
    fields: {
      'birth-year': 1966, 'birth-month': 8, 'retire-age': 66,
      wages: 95000, 'future-wages': 95000, 'avg-wages': 52000, 'years-worked': 30,
      'ss-override': 0,
      'traditional-balance': 300000, 'roth-balance': 80000, 'taxable-balance': 40000,
      'annual-contrib': 4000, 'employer-contrib': 2000,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_future_raise',
    description: 'Single, current pay $60k but expects $95k until a later retirement at 70',
    household: 'single',
    fields: {
      'birth-year': 1961, 'birth-month': 2, 'retire-age': 70,
      wages: 60000, 'future-wages': 95000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 450000, 'roth-balance': 120000, 'taxable-balance': 45000,
      'annual-contrib': 8000, 'employer-contrib': 4000,
      'return-rate': 3, 'annual-spending': 68000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_older_fra66',
    description: 'Single, born 1954 (FRA = 66 exactly), verifies factor() off a non-67 FRA',
    household: 'single',
    fields: {
      'birth-year': 1954, 'birth-month': 5, 'retire-age': 66,
      wages: 72000, 'future-wages': 72000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 380000, 'roth-balance': 90000, 'taxable-balance': 35000,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 58000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_earnings_test',
    description: 'Single, still working past 62 with earnings well above the 2026 limit',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 1, 'retire-age': 68,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 300000, 'roth-balance': 90000, 'taxable-balance': 30000,
      'annual-contrib': 5000, 'employer-contrib': 2500,
      'return-rate': 3, 'annual-spending': 62000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 60000,
    },
  },
  {
    id: 'couple_baseline',
    description: 'Couple, similar ages, both estimated (no overrides)',
    household: 'couple',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 65,
      wages: 70000, 'future-wages': 70000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1965, 'spouse-birth-month': 9, 'spouse-retire-age': 65,
      'spouse-wages': 45000, 'spouse-future-wages': 45000, 'spouse-avg-wages': 0, 'spouse-years-worked': 30,
      'spouse-ss-override': 0,
      'traditional-balance': 500000, 'roth-balance': 150000, 'taxable-balance': 70000,
      'annual-contrib': 6000, 'employer-contrib': 3000, 'spouse-contrib': 3000, 'spouse-employer-contrib': 1500,
      'return-rate': 3, 'annual-spending': 85000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'couple_staggered_retirement',
    description: 'Couple, same age, but spouse retires two years after the primary',
    household: 'couple',
    fields: {
      'birth-year': 1963, 'birth-month': 3, 'retire-age': 62,
      wages: 65000, 'future-wages': 65000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1963, 'spouse-birth-month': 3, 'spouse-retire-age': 64,
      'spouse-wages': 55000, 'spouse-future-wages': 55000, 'spouse-avg-wages': 0, 'spouse-years-worked': 30,
      'spouse-ss-override': 0,
      'traditional-balance': 550000, 'roth-balance': 100000, 'taxable-balance': 50000,
      'annual-contrib': 4000, 'employer-contrib': 2000, 'spouse-contrib': 3000, 'spouse-employer-contrib': 1500,
      'return-rate': 3, 'annual-spending': 78000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'couple_age_gap',
    description: 'Couple, spouse is 10 years younger (tests householdReadyAge bridging)',
    household: 'couple',
    fields: {
      'birth-year': 1960, 'birth-month': 1, 'retire-age': 65,
      wages: 80000, 'future-wages': 80000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1970, 'spouse-birth-month': 1, 'spouse-retire-age': 65,
      'spouse-wages': 50000, 'spouse-future-wages': 50000, 'spouse-avg-wages': 0, 'spouse-years-worked': 30,
      'spouse-ss-override': 0,
      'traditional-balance': 600000, 'roth-balance': 150000, 'taxable-balance': 80000,
      'annual-contrib': 5000, 'employer-contrib': 2500, 'spouse-contrib': 4000, 'spouse-employer-contrib': 2000,
      'return-rate': 3, 'annual-spending': 90000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'couple_mixed_ss_known',
    description: 'Couple, primary has a real SSA statement, spouse is estimated (the just-fixed mixed-household case)',
    household: 'couple',
    fields: {
      'birth-year': 1962, 'birth-month': 7, 'retire-age': 67,
      wages: 0, 'future-wages': 0, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 2600, 'ss-override-age': 67,
      'spouse-birth-year': 1963, 'spouse-birth-month': 2, 'spouse-retire-age': 65,
      'spouse-wages': 48000, 'spouse-future-wages': 48000, 'spouse-avg-wages': 0, 'spouse-years-worked': 30,
      'spouse-ss-override': 0,
      'traditional-balance': 480000, 'roth-balance': 120000, 'taxable-balance': 55000,
      'annual-contrib': 0, 'employer-contrib': 0, 'spouse-contrib': 0, 'spouse-employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 80000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
    ssKnown: 'yes',
    spouseSsKnown: 'no',
  },
  {
    id: 'couple_low_earner_spousal_excess',
    description: 'Couple, spouse own benefit well below half of primary PIA (spousal excess applies)',
    household: 'couple',
    fields: {
      'birth-year': 1961, 'birth-month': 10, 'retire-age': 67,
      wages: 150000, 'future-wages': 150000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1962, 'spouse-birth-month': 5, 'spouse-retire-age': 67,
      'spouse-wages': 15000, 'spouse-future-wages': 15000, 'spouse-avg-wages': 0, 'spouse-years-worked': 15,
      'spouse-ss-override': 0,
      'traditional-balance': 700000, 'roth-balance': 200000, 'taxable-balance': 100000,
      'annual-contrib': 0, 'employer-contrib': 0, 'spouse-contrib': 0, 'spouse-employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 95000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'single_portfolio_depletion',
    description: 'Single, high spending relative to savings (tests the depletion floor)',
    household: 'single',
    fields: {
      'birth-year': 1965, 'birth-month': 4, 'retire-age': 62,
      wages: 40000, 'future-wages': 40000, 'avg-wages': 0, 'years-worked': 20,
      'ss-override': 0,
      'traditional-balance': 60000, 'roth-balance': 10000, 'taxable-balance': 5000,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 2, 'annual-spending': 90000, horizon: 95,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'single_reinvest_early_ss',
    description: 'Single, claims-before-retirement checks reinvested into savings instead of spent',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 67,
      wages: 55000, 'future-wages': 55000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 300000, 'roth-balance': 80000, 'taxable-balance': 30000,
      'annual-contrib': 3000, 'employer-contrib': 1500,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 55000,
    },
    earlyUse: 'invest',
  },
  {
    id: 'single_pension_bridge',
    description: 'Single, retires at 62 with a $30k pension: bridge should net the pension out of spending',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 62,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 800000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 30000, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'couple_staggered_bridge',
    description: 'Couple, same age, you retire at 62 and spouse at 65: bridge runs from 65, not 62',
    household: 'couple',
    fields: {
      'birth-year': 1964, 'birth-month': 1, 'retire-age': 62,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1964, 'spouse-birth-month': 1, 'spouse-retire-age': 65,
      'spouse-wages': 50000, 'spouse-future-wages': 50000, 'spouse-avg-wages': 0, 'spouse-years-worked': 35,
      'spouse-ss-override': 0,
      'traditional-balance': 700000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0, 'spouse-contrib': 0, 'spouse-employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'single_already_retired',
    description: 'Single, age 69 today but entered a retirement age of 65 (already past)',
    household: 'single',
    fields: {
      'birth-year': 1957, 'birth-month': 1, 'retire-age': 65,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 500000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 30000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0,
    },
  },
  {
    id: 'couple_mixed_claim_spousal',
    description: 'Couple with a big earnings gap and a birth-date offset: mixed claim ages in the couple matrix',
    household: 'couple',
    fields: {
      'birth-year': 1963, 'birth-month': 8, 'retire-age': 67,
      wages: 160000, 'future-wages': 160000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1965, 'spouse-birth-month': 2, 'spouse-retire-age': 65,
      'spouse-wages': 20000, 'spouse-future-wages': 20000, 'spouse-avg-wages': 0, 'spouse-years-worked': 20,
      'spouse-ss-override': 0,
      'traditional-balance': 900000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0, 'spouse-contrib': 0, 'spouse-employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 90000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 0, 'spouse-countable-earnings': 0,
    },
  },
  {
    id: 'single_blank_defaults',
    description: 'Single, Quick-style inputs: future earnings and countable earnings left blank fall back to current pay',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 67,
      wages: 95000, 'future-wages': '', 'avg-wages': '', 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 500000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 70000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': '',
    },
  },
  {
    id: 'credit_work_past_fra',
    description: 'Single, works to 70 at $90k: full years withheld, then a partial FRA-year withholding ($1 per $3 over $65,160)',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 70,
      wages: 90000, 'future-wages': 90000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 600000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 65000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 90000,
    },
  },
  {
    id: 'credit_fractional_fra',
    description: 'Single, born 1958 (FRA 66y8m), works to 70: the FRA year holds only 8 months before FRA',
    household: 'single',
    fields: {
      'birth-year': 1958, 'birth-month': 5, 'retire-age': 70,
      wages: 80000, 'future-wages': 80000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 600000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 80000,
    },
  },
  {
    id: 'credit_under_limit',
    description: 'Single, works to 67 but earns under the 2026 limit: nothing withheld, nothing to credit',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 67,
      wages: 24000, 'future-wages': '', 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 400000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 50000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': '',
    },
  },
  {
    id: 'credit_couple_one_works',
    description: 'Couple, you retire at 62 (no earnings) while a younger spouse works to 67: withholding follows each own retirement age',
    household: 'couple',
    fields: {
      'birth-year': 1964, 'birth-month': 3, 'retire-age': 62,
      wages: 60000, 'future-wages': 60000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'spouse-birth-year': 1967, 'spouse-birth-month': 10, 'spouse-retire-age': 67,
      'spouse-wages': 70000, 'spouse-future-wages': 70000, 'spouse-avg-wages': 0, 'spouse-years-worked': 35,
      'spouse-ss-override': 0,
      'traditional-balance': 700000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 0, 'employer-contrib': 0, 'spouse-contrib': 0, 'spouse-employer-contrib': 0,
      'return-rate': 3, 'annual-spending': 80000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 60000, 'spouse-countable-earnings': 70000,
    },
  },
  {
    id: 'credit_invest_early_checks',
    description: 'Single, works to 67 at $75k, invests early checks: only the unwithheld part reaches savings',
    household: 'single',
    fields: {
      'birth-year': 1964, 'birth-month': 6, 'retire-age': 67,
      wages: 75000, 'future-wages': 75000, 'avg-wages': 0, 'years-worked': 35,
      'ss-override': 0,
      'traditional-balance': 300000, 'roth-balance': 0, 'taxable-balance': 0,
      'annual-contrib': 3000, 'employer-contrib': 1500,
      'return-rate': 3, 'annual-spending': 60000, horizon: 90,
      'pension-income': 0, 'other-income': 0, 'countable-earnings': 75000,
    },
    earlyUse: 'invest',
  },
];

module.exports = {SCENARIOS, personFields};
